const data = [
  "I'm baby migas kitsch blog, messenger bag cronut cloud bread af polaroid. Normcore art party unicorn, bitters vape pour-over ramps swag distillery af woke. Disrupt chillwave ethical squid copper mug tumeric. Church-key franzen lomo forage sustainable helvetica copper mug freegan beard sriracha raw denim. Polaroid squid tbh austin, biodiesel lo-fi flannel retro vaporware hell of mustache offal kinfolk yr yuccie.",
  "Etsy helvetica kogi fanny pack small batch irony swag. DIY freegan you probably haven't heard of them try-hard tilde DSA wolf hot chicken next level. DSA lo-fi narwhal artisan tote bag pug. Blog pour-over brunch, fashion axe food truck prism direct trade kogi godard irony viral bushwick chambray lumbersexual. Praxis cronut lyft vice butcher. Deep v cray swag hoodie VHS flannel prism pug tbh.",
  "Before they sold out celiac slow-carb vice edison bulb semiotics salvia gochujang chicharrones mumblecore tousled. PBR&B heirloom you probably haven't heard of them put a bird on it brunch disrupt irony neutra hoodie XOXO kogi. Hella organic hashtag narwhal next level try-hard trust fund actually glossier subway tile chambray semiotics street art. Etsy microdosing VHS locavore.",
  "Next level readymade ennui hammock retro wolf vape umami crucifix pop-up tbh offal direct trade. Tote bag blue bottle pitchfork, pour-over health goth ethical photo booth retro disrupt hoodie chillwave. Ugh organic YOLO, edison bulb vinyl shoreditch +1 fam tattooed typewriter celiac umami. Sustainable meh enamel pin, small batch portland kogi salvia. DSA readymade PBR&B post-ironic distillery quinoa retro. Letterpress plaid church-key twee coloring book.",
  "Actually literally raw denim adaptogen brooklyn. Semiotics brunch neutra everyday carry tofu freegan bicycle rights snackwave selfies gluten-free fam vape affogato. Literally meggings iPhone mumblecore. Green juice meh seitan disrupt salvia yuccie. Adaptogen hashtag pour-over, offal tacos celiac thundercats migas la croix wayfarers street art air plant. 3 wolf moon normcore letterpress chicharrones kitsch live-edge lyft stumptown marfa trust fund man braid street art gochujang vegan wayfarers. Ramps pour-over praxis taxidermy +1, food truck vinyl snackwave chicharrones cred celiac vexillologist shaman tofu beard.",
  "Bitters yuccie asymmetrical retro brunch.Whatever lo - fi kitsch retro letterpress polaroid health goth freegan intelligentsia brunch shabby chic hoodie schlitz truffaut.Mixtape polaroid swag, brunch sustainable pok pok tilde kinfolk seitan flannel literally vaporware small batch.Trust fund messenger bag narwhal venmo butcher poutine edison bulb subway tile pork belly polaroid succulents hexagon seitan.Blue bottle XOXO neutra, schlitz put a bird on it actually readymade cred viral ethical craft beer taxidermy cray bicycle rights synth.Master cleanse banjo typewriter raclette tacos shaman live - edge green juice plaid hexagon knausgaard flexitarian dreamcatcher jean shorts wayfarers.",
  "Vape hot chicken biodiesel squid listicle franzen. Butcher health goth praxis, hashtag yes plz polaroid sustainable pour-over vinyl brooklyn. Blog banjo flexitarian venmo slow-carb, offal cred listicle cronut drinking vinegar pinterest activated charcoal four loko hammock. Swag tumeric slow-carb, iPhone meggings waistcoat franzen cred semiotics vice beard tonx fanny pack single-origin coffee. Yuccie bicycle rights cloud bread fam butcher chillwave master cleanse 3 wolf moon truffaut kale chips. Prism DIY vice chicharrones man bun synth.",
  "Ramps snackwave occupy YOLO, migas fixie distillery williamsburg polaroid succulents photo booth. Intelligentsia pork belly la croix selfies, readymade raclette sustainable craft beer hoodie celiac tousled master cleanse affogato. Glossier hammock fam, keffiyeh before they sold out single-origin coffee marfa butcher yes plz stumptown tousled iPhone synth XOXO meh. Listicle artisan tumblr, taiyaki food truck kinfolk viral fingerstache yes plz la croix air plant vice lyft succulents chillwave. Twee organic ramps, umami marfa sustainable typewriter af kinfolk skateboard vegan knausgaard williamsburg wayfarers.",
];

export default data;
